language: cpp
sudo: false

matrix:
  include:
    - compiler: clang
      env: COMPILER=clang++-3.6 BACKEND=make EXTRAFLAGS=-DMETTLE_NO_STDLIB_EXTS
      addons: &clang-36
        apt:
          sources: &sources
            - boost-latest
            - llvm-toolchain-precise-3.6
            - llvm-toolchain-precise-3.7
            - ubuntu-toolchain-r-test
          packages:
            - clang-3.6
            - g++-5
            - libboost1.55-dev
            - libboost-iostreams1.55-dev
            - libboost-program-options1.55-dev
            - ninja-build
            - python-virtualenv
    - compiler: clang
      env: COMPILER=clang++-3.6 BACKEND=ninja EXTRAFLAGS=-DMETTLE_NO_STDLIB_EXTS
      addons: *clang-36
    - compiler: clang
      env: COMPILER=clang++-3.7 BACKEND=make EXTRAFLAGS=-DMETTLE_NO_STDLIB_EXTS
      addons: &clang-37
        apt:
          sources: *sources
          packages:
            - clang-3.7
            - g++-5
            - libboost1.55-dev
            - libboost-iostreams1.55-dev
            - libboost-program-options1.55-dev
            - ninja-build
            - python-virtualenv
    - compiler: clang
      env: COMPILER=clang++-3.7 BACKEND=ninja EXTRAFLAGS=-DMETTLE_NO_STDLIB_EXTS
      addons: *clang-37
    - os: osx
      osx_image: xcode7.2
      env: COMPILER=clang++ BACKEND=ninja
    - os: osx
      osx_image: xcode7.2
      env: COMPILER=clang++ BACKEND=ninja EXTRAFLAGS=-DMETTLE_NO_STDLIB_EXTS

cache:
  apt: true
  directories:
    - env

install:
  - |
    if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      brew update
      brew install python
      brew install ninja
      pip install virtualenv
    fi
  - 'if [ ! -f "env/bin/activate" ]; then virtualenv env; fi'
  - source env/bin/activate
  - pip install -U bfg9000
  - git clone https://github.com/jimporter/bencode.hpp.git
  - export CPATH=`pwd`/bencode.hpp/include
script:
  - |
    CXX=${COMPILER} CXXFLAGS="-Wall -Wextra -pedantic ${EXTRAFLAGS}" bfg9000 build --backend=${BACKEND}
    cd build
    ${BACKEND} test
