language: cpp
sudo: false

env:
  global:
    - BACKEND=ninja
    - COMMONFLAGS="-Wall -Wextra -pedantic -Werror"
    - PYTHON=python
    - PIP=pip

addons:
  apt:
    sources: &sources
      - boost-latest
      - ubuntu-toolchain-r-test
    packages: &packages
      - libboost1.55-dev
      - libboost-iostreams1.55-dev
      - libboost-program-options1.55-dev
      - ninja-build
      - python-virtualenv

cache:
  apt: true

matrix:
  include:
    - compiler: clang
      env: COMPILER=clang++-3.6
      addons:
        apt:
          sources:
            - *sources
            - llvm-toolchain-precise-3.6
          packages:
            - *packages
            - clang-3.6
            - libstdc++-5-dev

    - compiler: clang
      env: COMPILER=clang++-3.7
      addons:
        apt:
          sources:
            - *sources
            - llvm-toolchain-precise-3.7
          packages:
            - *packages
            - clang-3.7
            - libstdc++-5-dev

    - compiler: clang
      env: COMPILER=clang++-3.8
      addons:
        apt:
          sources:
            - *sources
            - llvm-toolchain-precise-3.8
          packages:
            - *packages
            - clang-3.8
            - libstdc++-5-dev

    - compiler: clang
      env: COMPILER=clang++-3.9
      addons:
        apt:
          sources:
            - *sources
            - llvm-toolchain-precise-3.9
          packages:
            - *packages
            - clang-3.9
            - libstdc++-5-dev

    - compiler: clang
      env: COMPILER=clang++-4.0
      addons:
        apt:
          sources:
            - *sources
            - llvm-toolchain-trusty-4.0
          packages:
            - *packages
            - clang-4.0
            - libstdc++-5-dev

    - compiler: clang
      env: COMPILER=clang++-5.0
      addons: &clang-50
        apt:
          sources:
            - *sources
            - llvm-toolchain-trusty-5.0
          packages:
            - *packages
            - clang-5.0
            - libstdc++-5-dev

    - compiler: clang
      env: COMPILER=clang++-5.0 BACKEND=make BUILD_ARGS="-j4"
      addons: *clang-50

    - compiler: gcc
      # Something about Travis and/or GCC has issues building in parallel with
      # ninja...
      env: COMPILER=g++-5 BUILD_ARGS="-j1" EXTRAFLAGS=-Wsuggest-override
      addons:
        apt:
          sources: *sources
          packages:
            - *packages
            - g++-5

    - compiler: gcc
      env: COMPILER=g++-6 BUILD_ARGS="-j1" EXTRAFLAGS=-Wsuggest-override
      addons:
        apt:
          sources: *sources
          packages:
            - *packages
            - g++-6

    - compiler: gcc
      env: COMPILER=g++-7 BUILD_ARGS="-j1" EXTRAFLAGS=-Wsuggest-override
      addons: &gcc-7
        apt:
          sources: *sources
          packages:
            - *packages
            - g++-7

    - compiler: gcc
      env: COMPILER=g++-7 BACKEND=make BUILD_ARGS="-j4" EXTRAFLAGS=-Wsuggest-override
      addons: *gcc-7

    - os: osx
      env: PYTHON=python2 PIP=pip2 COMPILER=clang++ BACKEND=ninja

    - os: osx
      env: PYTHON=python2 PIP=pip2 COMPILER=clang++ BACKEND=ninja EXTRAFLAGS=-DMETTLE_NO_STDLIB_EXTS

before_install:
  - |
    if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      shell_session_update() { :; }
      brew update
      brew install ${PYTHON} ninja
    else
      set -e
      virtualenv env && source env/bin/activate
    fi
  - ${PIP} install bfg9000
install:
  - ${PYTHON} scripts/vendorize_bencode.py
script:
  - |
    CXX=${COMPILER} CPPFLAGS="${COMMONFLAGS} ${EXTRAFLAGS}" 9k build --backend=${BACKEND}
    cd build
    ${BACKEND} test ${BUILD_ARGS}
