site_name: mettle
docs_dir: doc
theme: yeti

repo_url: https://github.com/jimporter/mettle/

pages:
- [index.md, Home]
- [writing-tests.md, User Guide, Writing Tests]
- [matchers.md, User Guide, Expectations and Matchers]
- [license.md, License]