site_name: mettle
docs_dir: doc
repo_url: https://github.com/jimporter/mettle/
theme: yeti

extra_css:
- css/extra.css

markdown_extensions:
- admonition

pages:
- [index.md, Home]
- [install.md, Installation]
- [tutorial.md, User Guide, Tutorial]
- [running-tests.md, User Guide, Running Tests]
- [writing-tests.md, User Guide, Writing Tests]
- [expectations.md, User Guide, Expectations]
- [built-in-matchers.md, User Guide, Built-in Matchers]
- [writing-matchers.md, User Guide, Writing Your Own Matchers]
- [developer.md, Developer Guide]
- [license.md, License]
