site_name: mettle
docs_dir: doc
theme: yeti
extra_css:
- css/extra.css

repo_url: https://github.com/jimporter/mettle/

pages:
- [index.md, Home]
- [install.md, Installation]
- [running-tests.md, User Guide, Running Tests]
- [writing-tests.md, User Guide, Writing Tests]
- [matchers.md, User Guide, Expectations and Matchers]
- [developer.md, Developer Guide]
- [license.md, License]
