name: build
on:
  pull_request:
  push:
  schedule:
  - cron: '0 0 1 * *'

env:
  COMMONFLAGS: '-Wall -Wextra -pedantic -Werror'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # GCC builds
          - {os: ubuntu-latest, compiler: gcc, version:  '7',
             flags: '-Wsuggest-override'}
          - {os: ubuntu-latest, compiler: gcc, version:  '8',
             flags: '-Wsuggest-override'}
          - {os: ubuntu-latest, compiler: gcc, version:  '9',
             flags: '-Wsuggest-override'}
          - {os: ubuntu-latest, compiler: gcc, version: '10',
             flags: '-Wsuggest-override'}

          # Clang builds
          - {os: ubuntu-latest, compiler: clang, version:  '6.0'}
          - {os: ubuntu-latest, compiler: clang, version:  '7'}
          - {os: ubuntu-latest, compiler: clang, version:  '8'}
          - {os: ubuntu-latest, compiler: clang, version:  '9'}
          - {os: ubuntu-latest, compiler: clang, version: '10'}

          # Windows builds
          - {os: windows-latest, version: '14.1', boost: '1_69_0'}
          - {os: windows-latest, version: '14.2', boost: '1_72_0'}

          # macOS builds
          - {os: macos-latest}
          - {os: macos-latest, flags: '-DMETTLE_NO_STDLIB_EXTS'}

          # Boost 1.58 builds
          # (Test 1.58 specifically because it has very strict rules for
          # Boost.Variant.)
          - {os: ubuntu-16.04, compiler: gcc, version: '9',
             boost_version: '1.58'}

          # C++20 builds
          - {os: ubuntu-latest, compiler: gcc, version: '10',
             flags: '--std=c++2a -Wsuggest-override'}
          - {os: ubuntu-latest, compiler: clang, version: '10',
             flags: '--std=c++2a'}
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Python dependencies
      run: |
        pip install bfg9000
    - name: Install Linux dependencies
      if: startsWith(matrix.os, 'ubuntu-')
      run: >
        sudo apt-get install
        ninja-build
        libboost${{ matrix.boost_version }}-dev
        libboost-iostreams${{ matrix.boost_version }}-dev
        libboost-program-options${{ matrix.boost_version }}-dev
    - name: Install Windows dependencies
      if: matrix.os == 'windows-latest'
      run: |
        cinst ninja
        ${gnomebase} = "https://ftp.gnome.org/pub/gnome/binaries/win32"
        curl -LO ${gnomebase}/dependencies/pkg-config_0.26-1_win32.zip
        curl -LO ${gnomebase}/glib/2.28/glib_2.28.8-1_win32.zip
        curl -LO ${gnomebase}/dependencies/gettext-runtime_0.18.1.1-2_win32.zip
        7z x -y pkg-config_0.26-1_win32.zip -oC:\pkg-config
        7z x -y glib_2.28.8-1_win32.zip -oC:\pkg-config
        7z x -y gettext-runtime_0.18.1.1-2_win32.zip -oC:\pkg-config
        echo "PKG_CONFIG=C:\pkg-config\bin\pkg-config.exe" >> ${env:GITHUB_ENV}
        echo "BOOST_INCLUDEDIR=${env:BOOST_ROOT_${{ matrix.boost }}}\include" >> ${env:GITHUB_ENV}
        echo "BOOST_LIBRARYDIR=${env:BOOST_ROOT_${{ matrix.boost }}}\lib" >> ${env:GITHUB_ENV}
        echo "CXXFLAGS=/WX ${{ matrix.flags }}" >> ${env:GITHUB_ENV}
    - name: Install macOS dependencies
      if: matrix.os == 'macos-latest'
      run: |
        brew install ninja pkg-config boost
    - name: Install gcc
      if: matrix.compiler == 'gcc'
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get update
        sudo apt-get install g++-${{ matrix.version }}
        echo "CXX=g++-${{ matrix.version }}" >> ${GITHUB_ENV}
        echo "CXXFLAGS=${COMMONFLAGS} ${{ matrix.flags }}" >> ${GITHUB_ENV}
    - name: Install clang
      if: matrix.compiler == 'clang'
      run: |
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key 2>/dev/null | sudo apt-key add -
        sudo add-apt-repository "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-${{ matrix.version }} main"
        sudo apt-get update
        sudo apt-get install clang-${{ matrix.version }}
        echo "CXX=clang++-${{ matrix.version }}" >> ${GITHUB_ENV}
        echo "CXXFLAGS=${COMMONFLAGS} ${{ matrix.flags }}" >> ${GITHUB_ENV}
    - name: Initialize MSVC ${{ matrix.version }}
      if: matrix.os == 'windows-latest'
      uses: ilammy/msvc-dev-cmd@v1
      with:
        toolset: ${{ matrix.version }}
    - name: Run tests
      run: |
        9k build --backend=ninja --vendorize
        cd build
        ninja test
